org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true

kotlin.code.style=official
android.aapt2FromMavenOverride=/tmp/opencode/android-sdk/build-tools/36.0.0/aapt2
